"""initial schema

Revision ID: 3efd7b1a065c
Revises: 
Create Date: 2026-09-20 22:19:11.290045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3efd7b1a065c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('actor', sa.String(length=512), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_index(op.f('ix_audit_log_object_id'), 'audit_log', ['object_id'], unique=False)
    op.create_index(op.f('ix_audit_log_object_type'), 'audit_log', ['object_type'], unique=False)
    op.create_table('contradictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_a_id', sa.String(length=64), nullable=False),
    sa.Column('claim_b_id', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('resolved_by', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contradictions_claim_a_id'), 'contradictions', ['claim_a_id'], unique=False)
    op.create_index(op.f('ix_contradictions_claim_b_id'), 'contradictions', ['claim_b_id'], unique=False)
    op.create_index(op.f('ix_contradictions_severity'), 'contradictions', ['severity'], unique=False)
    op.create_index(op.f('ix_contradictions_status'), 'contradictions', ['status'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('attributes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'kind', name='uq_entities_name_kind')
    )
    op.create_index(op.f('ix_entities_kind'), 'entities', ['kind'], unique=False)
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=False)
    op.create_table('entity_relations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_id', sa.String(length=64), nullable=False),
    sa.Column('to_id', sa.String(length=64), nullable=False),
    sa.Column('rel_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_relations_from_id'), 'entity_relations', ['from_id'], unique=False)
    op.create_index(op.f('ix_entity_relations_rel_type'), 'entity_relations', ['rel_type'], unique=False)
    op.create_index(op.f('ix_entity_relations_to_id'), 'entity_relations', ['to_id'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('insight_type', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('supporting_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_insight_type'), 'insights', ['insight_type'], unique=False)
    op.create_index(op.f('ix_insights_status'), 'insights', ['status'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_type'), 'reports', ['type'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=512), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_indexed_at'), 'sources', ['indexed_at'], unique=False)
    op.create_index(op.f('ix_sources_source_id'), 'sources', ['source_id'], unique=False)
    op.create_index(op.f('ix_sources_source_type'), 'sources', ['source_type'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_hash', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('section_tree', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.create_index(op.f('ix_documents_file_path'), 'documents', ['file_path'], unique=False)
    op.create_index(op.f('ix_documents_source_id'), 'documents', ['source_id'], unique=False)
    op.create_table('knowledge_objects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('content_summary', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_objects_lifecycle_state'), 'knowledge_objects', ['lifecycle_state'], unique=False)
    op.create_index(op.f('ix_knowledge_objects_source_id'), 'knowledge_objects', ['source_id'], unique=False)
    op.create_index(op.f('ix_knowledge_objects_status'), 'knowledge_objects', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_objects_title'), 'knowledge_objects', ['title'], unique=False)
    op.create_index(op.f('ix_knowledge_objects_type'), 'knowledge_objects', ['type'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('alternatives', sa.Text(), nullable=False),
    sa.Column('decision_text', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('affected_components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('author', sa.String(length=512), nullable=False),
    sa.Column('decided_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_knowledge_id'), 'decisions', ['knowledge_id'], unique=False)
    op.create_index(op.f('ix_decisions_status'), 'decisions', ['status'], unique=False)
    op.create_index(op.f('ix_decisions_title'), 'decisions', ['title'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('hypothesis_tested', sa.Text(), nullable=False),
    sa.Column('dataset', sa.String(length=1024), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('statistics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reproducibility', sa.Text(), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_knowledge_id'), 'experiments', ['knowledge_id'], unique=False)
    op.create_index(op.f('ix_experiments_status'), 'experiments', ['status'], unique=False)
    op.create_index(op.f('ix_experiments_title'), 'experiments', ['title'], unique=False)
    op.create_table('research_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('topic', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('validation_level', sa.String(length=64), nullable=False),
    sa.Column('related_modules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_items_knowledge_id'), 'research_items', ['knowledge_id'], unique=False)
    op.create_index(op.f('ix_research_items_status'), 'research_items', ['status'], unique=False)
    op.create_index(op.f('ix_research_items_title'), 'research_items', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_items_title'), table_name='research_items')
    op.drop_index(op.f('ix_research_items_status'), table_name='research_items')
    op.drop_index(op.f('ix_research_items_knowledge_id'), table_name='research_items')
    op.drop_table('research_items')
    op.drop_index(op.f('ix_experiments_title'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_status'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_knowledge_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_decisions_title'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_status'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_knowledge_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_knowledge_objects_type'), table_name='knowledge_objects')
    op.drop_index(op.f('ix_knowledge_objects_title'), table_name='knowledge_objects')
    op.drop_index(op.f('ix_knowledge_objects_status'), table_name='knowledge_objects')
    op.drop_index(op.f('ix_knowledge_objects_source_id'), table_name='knowledge_objects')
    op.drop_index(op.f('ix_knowledge_objects_lifecycle_state'), table_name='knowledge_objects')
    op.drop_table('knowledge_objects')
    op.drop_index(op.f('ix_documents_source_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_path'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_sources_source_type'), table_name='sources')
    op.drop_index(op.f('ix_sources_source_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_indexed_at'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_reports_type'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_insights_status'), table_name='insights')
    op.drop_index(op.f('ix_insights_insight_type'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_entity_relations_to_id'), table_name='entity_relations')
    op.drop_index(op.f('ix_entity_relations_rel_type'), table_name='entity_relations')
    op.drop_index(op.f('ix_entity_relations_from_id'), table_name='entity_relations')
    op.drop_table('entity_relations')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_kind'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_contradictions_status'), table_name='contradictions')
    op.drop_index(op.f('ix_contradictions_severity'), table_name='contradictions')
    op.drop_index(op.f('ix_contradictions_claim_b_id'), table_name='contradictions')
    op.drop_index(op.f('ix_contradictions_claim_a_id'), table_name='contradictions')
    op.drop_table('contradictions')
    op.drop_index(op.f('ix_audit_log_object_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_object_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
